from enum import Enum


class QuestionType(Enum):

    AIRPORT = "AIRPORT"
    TIME = "TIME"
    WIND_DIRECTION = "WIND_DIRECTION"
    WIND_SPEED = "WIND_SPEED"
    WIND_GUST = "WIND_GUST"
    ALTIMETER = "ALTIMETER"
    TEMPERATURE = "TEMPERATURE"
    DEWPOINT = "DEWPOINT"
    VISIBILITY = "VISIBILITY"
    CLOUD_COVERAGE = "CLOUD_COVERAGE"
    CLOUD_HEIGHT_COLLECTIVE = "CLOUD_HEIGHT_COLLECTIVE"
    CLOUD_HEIGHT_INDIVIDUAL = "CLOUD_HEIGHT_INDIVIDUAL"
    WEATHER_CODES = "WEATHER_CODES"
    REMARKS_CODES = "REMARKS_CODES"
    REMARKS_TEMPERATURE_DECIMAL = "REMARKS_TEMPERATURE_DECIMAL"
    REMARKS_DEWPOINT_DECIMAL = "REMARKS_TEMPERATURE_DECIMAL"
    REMARKS_SEA_LEVEL_PRESSURE = "REMARKS_SEA_LEVEL_PRESSURE"


    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)
